# Generated by Django 5.1.5 on 2025-01-18 19:21

import localflavor.pk.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=localflavor.pk.models.PKPostCodeField(blank=True, max_length=5),
        ),
    ]
