# Generated by Django 5.2.1 on 2025-06-13 17:42

import django.db.models.deletion
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='brands',
            field=models.CharField(choices=[('bmw', 'BMW'), ('mercedes benz', 'Mercedes Benz'), ('audi', 'Audi'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('jaguar', 'Jaguar'), ('land rover', 'Land Rover'), ('bentley', 'Bentley'), ('bugatti', 'Bugatti'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('honda', 'Honda'), ('toyota', 'Toyota'), ('chevrolet', 'Chevrolet'), ('porsche', 'Porsche')], default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='list',
            name='color',
            field=models.CharField(default='White', max_length=24),
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='list',
            name='engine',
            field=models.CharField(default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(default='None', upload_to=main.utils.user_listing_path),
        ),
        migrations.AddField(
            model_name='list',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AddField(
            model_name='list',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='model',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='list',
            name='trasnmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='None', max_length=24),
        ),
        migrations.AddField(
            model_name='list',
            name='vin',
            field=models.CharField(default='None', max_length=17),
        ),
    ]
