# Generated by Django 5.2.1 on 2025-06-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_list_brands_list_color_list_description_list_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='color',
            field=models.CharField(default='None', max_length=24),
        ),
    ]
